services:
  app:
    build: .
    container_name: mailer_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - app_data:/app/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    user: "1000:1000"
    depends_on:
      - redis

  redis:
    image: redis:8.2-alpine
    container_name: mailer_redis
    restart: unless-stopped
    expose:
      - "6379"
volumes:
  app_data:


